### PR TITLE
Add support for Python 3.11

### PR DESCRIPTION
**Pull request by jmsmkn**
Currently `pylibjpeg-openjpeg` will not build under Python 3.11 due to some changes that were fixed in Cython 0.29.25 (https://github.com/cython/cython/pull/4428). This PR upgrades cython, regenerating `_openjpeg.c` directly from `_openjpeg.pyx`. The dependencies on numpy are also updated as 3.11 support was not added there until [1.23.2](https://numpy.org/devdocs/release/1.23.2-notes.html).

### CODE REVIEW

**Review by mrbean-bremen — APPROVED** [review]
Thanks, that looks good! I guess you already did test the packages locally?

**Comment by jmsmkn** [comment]
> Thanks, that looks good! I guess you already did test the packages locally?

Beyond the GitHub Actions CI I have built `pylibjpeg_openjpeg-1.3.1-cp311-cp311-linux_x86_64.whl` locally using Python 3.11.2 and ran our tests that decode some HTJ2K frames using `openjpeg.decode`, no changes from v1.3.1.

**Comment by mrbean-bremen** [comment]
Thank you!

**Comment by mrbean-bremen** [comment]
Hm, after merging building wheels for Python 3.11 failed in the release workflow...

**Comment by jmsmkn** [comment]
> Hm, after merging building wheels for Python 3.11 failed in the release workflow...

Sorry about that, I think I have the fix.

**Pull request merged**
